### ISSUE TITLE
Schema Beta - Display Dropdown Disabled

### ISSUE THREAD

**Issue by unkrich** [streamdal/streamdal#151]
Currently the dropdown for choosing a display option on the Schema feature is disabled - it's in Beta, so to be expected, but we might consider removing the dropdown until options are available to reduce confusion.

<img width="314" alt="image" src="https://github.com/streamdal/streamdal/assets/15347345/9cb12525-db94-43eb-ac2d-b465fd487909">

**Comment by dselans** [comment]
Agreed. Console has been updated - no more dropdown.
