### ISSUE TITLE
chore: Implement usage telemetry

### ISSUE THREAD

**Issue by dselans** [streamdal/streamdal#7]
In order to better understand how `streamdal` is being used, we need to have some sort of usage-based telemetry.

This is the current, proposed list of metrics we intend to collect:

## SDK

1. Language
1. Version
1. OS
1. Arch
1. Number of .Process() calls

## Shims

1. Language
1. Version
1. OS
1. Arch
1. Consumer / producer component type

## `streamdal-server`

1. Version
1. OS
1. Arch
1. `streamdal-server` uptime
1. Cluster size (how do we get this?)
1. Number of service groups
1. Number of consumer components
1. Number of producer components
1. Avg throughput for consumers
1. Avg throughput for producers

## `streamdal-console`

1. Email (on first load)
1. Version
1. First action taken by users
1. Browser version used to load UI

**Comment by uzarubin** [comment]
Lets add data stores when shims get released.
